#
# Module manifest for module 'TIKSN-PowerShell-Cmdlets'
#
# Generated by: Tigran TIKSN Thorosyan
#
# Generated on: 08/14/2015
#

@{

# Script module or binary module file associated with this manifest.
# ModuleToProcess = 'Cmdlets.Core.dll'
RootModule = 'Cmdlets.Core.dll'

# Version number of this module.
ModuleVersion = '1.2.0.0'

# ID used to uniquely identify this module
GUID = '852b7459-fcef-4c8d-96dd-049c344b88ad'

# Author of this module
Author = 'Tigran TIKSN Thorosyan'

# Company or vendor of this module
CompanyName = 'TIKSN Development'

# Copyright statement for this module
Copyright = '(c) 2015 TIKSN Development. All rights reserved.'

# Description of the functionality provided by this module
Description = 'TIKSN PowerShell Cmdlets is a PowerShell binary module which provides collection of useful cmdlets.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'Autofac.dll',
    'Autofac.Extensions.DependencyInjection.dll',
    'ConsoleTables.dll',
    'Exceptionless.Signed.dll',
    'LiteGuard.dll',
    'Microsoft.ApplicationInsights.dll',
    'Microsoft.AspNetCore.Hosting.Abstractions.dll',
    'Microsoft.AspNetCore.Hosting.Server.Abstractions.dll',
    'Microsoft.AspNetCore.Http.Abstractions.dll',
    'Microsoft.AspNetCore.Http.Features.dll',
    'Microsoft.Data.Edm.dll',
    'Microsoft.Data.OData.dll',
    'Microsoft.EntityFrameworkCore.dll',
    'Microsoft.Extensions.Caching.Abstractions.dll',
    'Microsoft.Extensions.Caching.Memory.dll',
    'Microsoft.Extensions.Configuration.Abstractions.dll',
    'Microsoft.Extensions.Configuration.dll',
    'Microsoft.Extensions.DependencyInjection.Abstractions.dll',
    'Microsoft.Extensions.DependencyInjection.dll',
    'Microsoft.Extensions.FileProviders.Abstractions.dll',
    'Microsoft.Extensions.Localization.Abstractions.dll',
    'Microsoft.Extensions.Localization.dll',
    'Microsoft.Extensions.Logging.Abstractions.dll',
    'Microsoft.Extensions.Logging.Debug.dll',
    'Microsoft.Extensions.Logging.dll',
    'Microsoft.Extensions.Options.dll',
    'Microsoft.Extensions.Primitives.dll',
    'Microsoft.Win32.Primitives.dll',
    'Microsoft.Win32.Registry.dll',
    'Microsoft.WindowsAzure.Storage.dll',
    'Newtonsoft.Json.dll',
    'Nito.AsyncEx.Context.dll',
    'Nito.AsyncEx.Tasks.dll',
    'Nito.Disposables.dll',
    'Cmdlets.Core.dll',
    'Remotion.Linq.dll',
    'Serilog.dll',
    'Serilog.Extensions.Logging.dll',
    'System.AppContext.dll',
    'System.Collections.Immutable.dll',
    'System.Console.dll',
    'System.Diagnostics.DiagnosticSource.dll',
    'System.Diagnostics.Tracing.dll',
    'System.Globalization.Calendars.dll',
    'System.Interactive.Async.dll',
    'System.IO.Compression.dll',
    'System.IO.Compression.ZipFile.dll',
    'System.IO.dll',
    'System.IO.FileSystem.dll',
    'System.IO.FileSystem.Primitives.dll',
    'System.Linq.dll',
    'System.Linq.Expressions.dll',
    'System.Management.Automation.dll',
    'System.Net.Http.dll',
    'System.Net.Sockets.dll',
    'System.Reactive.Core.dll',
    'System.Reactive.Interfaces.dll',
    'System.Reactive.Linq.dll',
    'System.Reflection.dll',
    'System.Reflection.TypeExtensions.dll',
    'System.Runtime.CompilerServices.Unsafe.dll',
    'System.Runtime.dll',
    'System.Runtime.Extensions.dll',
    'System.Runtime.InteropServices.dll',
    'System.Runtime.InteropServices.RuntimeInformation.dll',
    'System.Security.Cryptography.Algorithms.dll',
    'System.Security.Cryptography.Encoding.dll',
    'System.Security.Cryptography.Primitives.dll',
    'System.Security.Cryptography.X509Certificates.dll',
    'System.Spatial.dll',
    'System.Text.Encodings.Web.dll',
    'System.Text.RegularExpressions.dll',
    'System.Xml.ReaderWriter.dll',
    'TIKSN.Core.dll',
    'TIKSN.LanguageLocalization.dll',
    'TIKSN.RegionLocalization.dll')

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


